Repository ripe-tech/pconvert-rust, pull requests merged in 2021-01, with the labels that each got.

#33 fix: initial fix for the wrong param order
  README.md
  assets/mozilla/destination.png
  assets/mozilla/source.png
  examples/python/blend_images_mozilla.py
  examples/wasm/index.html
  examples/wasm/index.js
  src/blending/mod.rs
  src/cli.rs
  src/pymodule/mod.rs
  src/utils.rs
  src/wasm/README.md
  src/wasm/benchmark.rs
  src/wasm/mod.rs
Labels: bug, fast-track

#34 Add initial unit test to define structure
  .github/workflows/main.yml
  src/benchmark.rs
  src/blending/mod.rs
  src/cli.rs
  src/lib.rs
  src/parallelism.rs
  src/test/mod.rs
  src/utils.rs
Labels: enhancement, unit-testing

#35 Clippy compliance
  build.rs
Labels: enhancement
